// Auto-generated from data/map/tool_structural_mappings_20260819.json
// Coordinate source: Game8 map tool (assumed 0-256 reference space).
// Normalized to 0-100 percent of base.webp width/height.

export type MarkerType =
  | "beacon"
  | "boss"
  | "collectible"
  | "corruptedStatue"
  | "dungeon"
  | "enemy"
  | "gate"
  | "keyItem"
  | "mapFragment"
  | "shell"
  | "sidearm"
  | "tarstone"
  | "weapon";

export type MapMarker = {
  id: string;
  title: string;
  description: string;
  type: MarkerType;
  classification: string;
  x: number;
  y: number;
  area: string | null;
  region: string | null;
};

export const mapMarkers: MapMarker[] = [
  {
    id: "1556530",
    title: "Marrow Keep",
    description: "After finishing the Prologue, this area will be your main base. ",
    type: "beacon",
    classification: "Beacon",
    x: 50.059,
    y: 46.926,
    area: "World Map",
    region: null,
  },
  {
    id: "1556531",
    title: "Widow Overlook",
    description: "This is one of the first activated beacons when you exit the Marrow Keep for the first time.",
    type: "beacon",
    classification: "Beacon",
    x: 64.473,
    y: 49.242,
    area: "World Map",
    region: null,
  },
  {
    id: "1556532",
    title: "Corrupted Statue - Widow’s Overlook",
    description: "This corrupted statue can be found north of the Widow's Overlook Beacon.",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 66.074,
    y: 49.535,
    area: "World Map",
    region: null,
  },
  {
    id: "1556533",
    title: "Martyr’s Tomb",
    description: "This dungeon is found inside an abandoned church overlooking the Great Arbiter of Flesh from a cliff.",
    type: "dungeon",
    classification: "Dungeon",
    x: 61.582,
    y: 52.152,
    area: "World Map",
    region: null,
  },
  {
    id: "1556534",
    title: "Shrine of Trials",
    description: "This dungeon can only be accessed by ",
    type: "dungeon",
    classification: "Dungeon",
    x: 64.746,
    y: 52.645,
    area: "World Map",
    region: null,
  },
  {
    id: "1556535",
    title: "Mushroom Village",
    description: "This beacon can be found inside Mushroom Village. Near enemy mob and large bonfire.",
    type: "beacon",
    classification: "Beacon",
    x: 63.961,
    y: 55.961,
    area: "World Map",
    region: null,
  },
  {
    id: "1556536",
    title: "Corrupted Statue - Mushroom Village Gate",
    description: "This corrupted statue can be found north of the Mushroom Village Gate Beacon.",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 62.711,
    y: 60.645,
    area: "World Map",
    region: null,
  },
  {
    id: "1556537",
    title: "Ritual Grounds",
    description: "This dungeon can be found south of the Mushroom Village, behind the house and gravestone where you find Tiel's Shell.",
    type: "dungeon",
    classification: "Dungeon",
    x: 60.234,
    y: 54.996,
    area: "World Map",
    region: null,
  },
  {
    id: "1556538",
    title: "Mushroom Village Gate",
    description: "This beacon can be found past the Mushroom Village beacon when you head east. This is also found just in front of the Gate leading to the Gutten Mire. ",
    type: "beacon",
    classification: "Beacon",
    x: 60.984,
    y: 60.695,
    area: "World Map",
    region: null,
  },
  {
    id: "1556539",
    title: "Glutten Mire",
    description: "This gate is found behind the Mushroom Village Gate beacon. This also acts as a fast travel point for Mether's Breath allowing you to choose between Seeping Mire, Sunken Village, and Magdalena's Glade. ",
    type: "gate",
    classification: "Gate",
    x: 60.883,
    y: 61.477,
    area: "World Map",
    region: null,
  },
  {
    id: "1556540",
    title: "Tiel, The Acolyte",
    description: "From the Widow's Overlook beacon, head southeast until you reach a fence structure with two torches at the entrance. Go inside, then turn left to access Tiel's corpse. You will receive the shell afterwards.",
    type: "shell",
    classification: "Shell",
    x: 60.73,
    y: 54.469,
    area: "World Map",
    region: null,
  },
  {
    id: "1556541",
    title: "Axe＆Dagger",
    description: "You can pick up the Axe & Dagger from the Shrine of Trials Dungeon near the Mushroom Village Beacon. This requires finding the Chapel Key to unlock the Dungeon. ",
    type: "weapon",
    classification: "Weapon",
    x: 64.789,
    y: 52.84,
    area: "World Map",
    region: null,
  },
  {
    id: "1560908",
    title: "Outskirts of Mammon",
    description: "This is one of the first beacons you can travel to when you leave Marrow Keep for the first time. ",
    type: "beacon",
    classification: "Beacon",
    x: 42.766,
    y: 49.148,
    area: "World Map",
    region: null,
  },
  {
    id: "1560909",
    title: "Acolyte’s Stone",
    description: "The Acolyte's Stone can be purchased from Merrick in the Marrow Keep.",
    type: "tarstone",
    classification: "Tarstone",
    x: 49.738,
    y: 47.434,
    area: "World Map",
    region: null,
  },
  {
    id: "1560910",
    title: "Unwieldly Stone",
    description: "The Unwieldly Stone can be purchased from Merrick in the Marrow Keep.",
    type: "tarstone",
    classification: "Tarstone",
    x: 49.727,
    y: 47.285,
    area: "World Map",
    region: null,
  },
  {
    id: "1560911",
    title: "Genessa, The Wayward",
    description: "To obtain Genessa, start by heading to the Revenant Graves and look for an area of foliage with red petals surrounded by Sesters. Look for the Sester's Censer and interact with it to be transported to a different area. Defeat Sester Secundus and Hand the Sester's Censer over to the Stray Sester in Meadow's Keep. Watch the memory play out, and you'll receive Genessa's shell.",
    type: "shell",
    classification: "Shell",
    x: 39.191,
    y: 57.871,
    area: "World Map",
    region: null,
  },
  {
    id: "1560912",
    title: "Corrupted Statue - Ritual Grounds",
    description: "This corrupted statue can be found inside the Ritual Grounds dungeon.",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 60.211,
    y: 55.184,
    area: "World Map",
    region: null,
  },
  {
    id: "1560913",
    title: "Wounding Stone",
    description: "The Wounding Stone can be found in a chest near where you pick up the Shell of Tiel, the Acolyte.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.434,
    y: 54.629,
    area: "World Map",
    region: null,
  },
  {
    id: "1560914",
    title: "Chapel Key",
    description: "This key can be found on some rope near the dancing old ladies with the bonfire. Pass through the stone arch to see the statue holding the key. ",
    type: "keyItem",
    classification: "Key Item",
    x: 60.848,
    y: 55.512,
    area: "World Map",
    region: null,
  },
  {
    id: "1560915",
    title: "Map of Fainweald 【4】",
    description: "This map fragment can be found on an elevated platform south of the Widow's Overlook beacon and west of Tiel, the Acolyte's location. ",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 60.957,
    y: 53.207,
    area: "World Map",
    region: null,
  },
  {
    id: "1560916",
    title: "Obisidian Lathe",
    description: "This key item can be looted from the Martyr's Tomb, a dungeon found in a church past the Great Arbiter of Flesh in Widow's Overlook. ",
    type: "keyItem",
    classification: "Key Item",
    x: 61.477,
    y: 52.309,
    area: "World Map",
    region: null,
  },
  {
    id: "1560917",
    title: "Parasitic Stone",
    description: "The Parasitic Stone can be looted from the Martyr's Tomb, a dungeon found in a church past the Great Arbiter of Flesh in Widow's Overlook. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 61.578,
    y: 52.039,
    area: "World Map",
    region: null,
  },
  {
    id: "1560918",
    title: "Arbiter’s Prize",
    description: "The Arbiter's Prize is a loot drop from defeating the Great Arbiter of Flesh in Widow's Overlook.",
    type: "tarstone",
    classification: "Tarstone",
    x: 62.223,
    y: 51.539,
    area: "World Map",
    region: null,
  },
  {
    id: "1560919",
    title: "Emberseed Stone",
    description: "The Emberseed Stone is found in a chest inside the Mushroom Village Beacon in the Passenger's Shrine. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 64.016,
    y: 55.937,
    area: "World Map",
    region: null,
  },
  {
    id: "1560920",
    title: "One Legged Wolf",
    description: "This beacon is found north of the Mushroom Village Gate beacon just past the Corrupted Statue. You will need Mether's Breath to unlock the area leading to this. ",
    type: "beacon",
    classification: "Beacon",
    x: 65.0,
    y: 62.352,
    area: "World Map",
    region: null,
  },
  {
    id: "1560921",
    title: "Retribution Stone",
    description: "The Retribution Stone is obtained as a reward for clearing the corrupted statue can be found north of the Widow's Overlook Beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 66.098,
    y: 49.586,
    area: "World Map",
    region: null,
  },
  {
    id: "1560922",
    title: "Map of Fainweald 【5】",
    description: "This map fragment can be found near a rockwall just north of the One Legged Wolf beacon. ",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 66.375,
    y: 62.313,
    area: "World Map",
    region: null,
  },
  {
    id: "1560923",
    title: "Map of Fainweald 【3】",
    description: "This map fragment can be found near a cliff north of the Widow's Overlook beacon.",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 69.316,
    y: 48.629,
    area: "World Map",
    region: null,
  },
  {
    id: "1560924",
    title: "Proxima, The Broodseeker",
    description: "Head northwest of the Blackridge Pass beacon. Find the area guarded by an Infested Stalker. Enter the beacon and  you will then find Proxima's corpse inside.",
    type: "shell",
    classification: "Shell",
    x: 71.578,
    y: 51.758,
    area: "World Map",
    region: null,
  },
  {
    id: "1560925",
    title: "Flooded Village",
    description: "This dungeon can be found north of the Widow's Overlook. Its entrance is hidden via enchantment. Pass through the stone arch to reveal the doorway.",
    type: "dungeon",
    classification: "Dungeon",
    x: 70.562,
    y: 49.141,
    area: "World Map",
    region: null,
  },
  {
    id: "1560926",
    title: "Forgotten Crossbow",
    description: "Accessible by opening the locked area with the damp key.",
    type: "sidearm",
    classification: "Sidearm",
    x: 70.605,
    y: 49.293,
    area: "World Map",
    region: null,
  },
  {
    id: "1561534",
    title: "Blackridge Pass Beacon",
    description: "This beacon is found north of the Widow's Overlook beacon and south of the Flooded Village Dungeon. ",
    type: "beacon",
    classification: "Beacon",
    x: 69.449,
    y: 50.082,
    area: "World Map",
    region: null,
  },
  {
    id: "1561535",
    title: "Seeping Mire",
    description: "This beacon is found inside the Glutted Mire, an unmapped area behind the Mushroom Village Gate. ",
    type: "beacon",
    classification: "Beacon",
    x: 60.789,
    y: 62.039,
    area: "World Map",
    region: null,
  },
  {
    id: "1561536",
    title: "Sunken Village",
    description: "This beacon is found inside the Glutted Mire, an unmapped area behind the Mushroom Village Gate. ",
    type: "beacon",
    classification: "Beacon",
    x: 60.762,
    y: 62.359,
    area: "World Map",
    region: null,
  },
  {
    id: "1561537",
    title: "Corroded Stone",
    description: "The Corroded Stone can be found in a chest inside the Sunken Village Beacon in the Glutted Mire.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.629,
    y: 62.234,
    area: "World Map",
    region: null,
  },
  {
    id: "1561538",
    title: "Auspicious Stone",
    description: "Light the three candles as an offering to unlock the chest in the Mushroom Village to obtain the Auspicious Stone.",
    type: "tarstone",
    classification: "Tarstone",
    x: 63.012,
    y: 54.441,
    area: "World Map",
    region: null,
  },
  {
    id: "1561539",
    title: "Magdalena’s Memento",
    description: "The Magdalena's Memento is a loot drop from defeating Magdalena, Lady of the Woods.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.629,
    y: 62.633,
    area: "World Map",
    region: null,
  },
  {
    id: "1561540",
    title: "Marksman’s Stone",
    description: "Collect the Marksman's Stone from a chest past the Corrupted Statue near the Mushroom Village Gate Beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 62.629,
    y: 60.531,
    area: "World Map",
    region: null,
  },
  {
    id: "1561541",
    title: "Siegebreaker’s Stone",
    description: "Light the three candles as an offering to unlock the chest in the Sunken village and get the Siegebreaker's Stone.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.848,
    y: 61.773,
    area: "World Map",
    region: null,
  },
  {
    id: "1561542",
    title: "Volatile Fragment",
    description: "Defeat Vrannic, the Grand Illusionist in the Hall of Illusions inside the Mushroom Village Gate Beacon to obtain the Volatile Fragment.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.957,
    y: 60.805,
    area: "World Map",
    region: null,
  },
  {
    id: "1561543",
    title: "Etching Needles",
    description: "This key item is found in a chest past the Tarblighted Shepherd just before the boss fight area for Magdalena, Lady of the Woods.",
    type: "keyItem",
    classification: "Key Item",
    x: 60.824,
    y: 62.461,
    area: "World Map",
    region: null,
  },
  {
    id: "1561544",
    title: "Holding Cells",
    description: "This dungeon is found inside a well near the edge of the Blackridge Hamlet. ",
    type: "dungeon",
    classification: "Dungeon",
    x: 66.285,
    y: 52.312,
    area: "World Map",
    region: null,
  },
  {
    id: "1561545",
    title: "Coward’s Retreat",
    description: "This dungeon is found along a rocky wall just east of the Blackridge Pass beacon. ",
    type: "dungeon",
    classification: "Dungeon",
    x: 68.906,
    y: 52.441,
    area: "World Map",
    region: null,
  },
  {
    id: "1562840",
    title: "Deserted Mine",
    description: "This dungeon is found east of Mushroom Village if you go past the area where you meet Hilga and Grom. ",
    type: "dungeon",
    classification: "Dungeon",
    x: 65.156,
    y: 60.031,
    area: "World Map",
    region: null,
  },
  {
    id: "1562841",
    title: "Magdalena’s Glade",
    description: "This beacon will spawn inside the Glutten Mire after you defeat Magdalena, Lady of the Woods. ",
    type: "beacon",
    classification: "Beacon",
    x: 60.762,
    y: 62.652,
    area: "World Map",
    region: null,
  },
  {
    id: "1562842",
    title: "Troubadour’s Lute",
    description: "The Troubadour's Lute is found inside the One-Legged Wolf Tavern. It is located to the left of the performer facing the stage.",
    type: "sidearm",
    classification: "Sidearm",
    x: 64.035,
    y: 63.945,
    area: "World Map",
    region: null,
  },
  {
    id: "1562843",
    title: "Map of Fainweald 【2】",
    description: "This fragment can be found along the ramparts of the citadel on the top floor.",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 68.691,
    y: 38.078,
    area: "World Map",
    region: null,
  },
  {
    id: "1562844",
    title: "Citadel of Penance",
    description: "This beacon will be found on the top floors of the Citadel of Penance. The easiest way to get here is to exploit the teleportation from the ruins north of the One Legged Wolf beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 71.508,
    y: 39.105,
    area: "World Map",
    region: null,
  },
  {
    id: "1562845",
    title: "Grudge Stone",
    description: "The Grudge Stone can be looted from a chest near the Citadel of Penance beacon. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 71.219,
    y: 39.125,
    area: "World Map",
    region: null,
  },
  {
    id: "1562846",
    title: "Eredrim, The Venerable",
    description: "You can find Eredrim inside the boss area of the Citadel of Penance where you fight The Warden. ",
    type: "shell",
    classification: "Shell",
    x: 69.348,
    y: 38.637,
    area: "World Map",
    region: null,
  },
  {
    id: "1562847",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 65.703,
    y: 69.305,
    area: "World Map",
    region: null,
  },
  {
    id: "1562848",
    title: "Heart of Vatra",
    description: "Head to the Temple of Vatra, which is located northeast of the One-Legged Wolf Tavern. Once inside, continue heading north until you reach the end and collect the Heart of Vatra. Then, head back to the One-Legged Wolf Tavern, give the Heart of Vatra to Gragu, and play out the memory to obtain his shell.",
    type: "keyItem",
    classification: "Key Item",
    x: 62.313,
    y: 73.031,
    area: "World Map",
    region: null,
  },
  {
    id: "1562849",
    title: "Gragu, The Insatiable",
    description: "Head to the Temple of Vatra, which is located northeast of the One-Legged Wolf Tavern. Once inside, continue heading north until you reach the end and collect the Heart of Vatra. Then, head back to the One-Legged Wolf Tavern, give the Heart of Vatra to Gragu, and play out the memory to obtain his shell.",
    type: "shell",
    classification: "Shell",
    x: 63.863,
    y: 64.004,
    area: "World Map",
    region: null,
  },
  {
    id: "1562850",
    title: "Corrupted Statue - Central Fainweald",
    description: "This corrupted statue is found in the center of Fainweald with the nearest beacon being the one in Mushroom Village. ",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 67.598,
    y: 60.148,
    area: "World Map",
    region: null,
  },
  {
    id: "1562851",
    title: "Grisha Hunting Grounds",
    description: "This dungeon is found northeast of the Mushroom Village beacon. It will be a hole in a rocky wall.",
    type: "dungeon",
    classification: "Dungeon",
    x: 69.215,
    y: 57.723,
    area: "World Map",
    region: null,
  },
  {
    id: "1562852",
    title: "Unyielding Stone",
    description: "The Unyielding Stone is obtained as a reward for cleansing the Corrupted Statue in Central Fainweald.",
    type: "tarstone",
    classification: "Tarstone",
    x: 67.586,
    y: 60.195,
    area: "World Map",
    region: null,
  },
  {
    id: "1562853",
    title: "Berserker’s Stone",
    description: "The Berserker's Stone can be found in a chest after making 3 offerings in the Temple of Vatra.",
    type: "tarstone",
    classification: "Tarstone",
    x: 63.609,
    y: 73.105,
    area: "World Map",
    region: null,
  },
  {
    id: "1565344",
    title: "Stonebled Gate",
    description: "This beacon can be found down inside a cave just before the Sanguine Caverns Gate, with a trail of blood leading to it.",
    type: "beacon",
    classification: "Beacon",
    x: 79.703,
    y: 48.527,
    area: "World Map",
    region: null,
  },
  {
    id: "1565345",
    title: "Nochtean Gate",
    description: "This gate is found at the very end of the Ruins of Nochte and is the first beacon to cleanse in order to enter the Prisoner's Domain.",
    type: "beacon",
    classification: "Beacon",
    x: 53.246,
    y: 32.461,
    area: "World Map",
    region: null,
  },
  {
    id: "1565346",
    title: "Outskirts of Nochte",
    description: "This beacon is found in the heart of The Hag's Path, south of the Citadel of Penance.",
    type: "beacon",
    classification: "Beacon",
    x: 58.824,
    y: 37.922,
    area: "World Map",
    region: null,
  },
  {
    id: "1565347",
    title: "Gloomshade Grove",
    description: "This beacon is found on a cliffside east of the Citadel of Penance. ",
    type: "beacon",
    classification: "Beacon",
    x: 69.684,
    y: 42.621,
    area: "World Map",
    region: null,
  },
  {
    id: "1565348",
    title: "Sester’s Gate",
    description: "This beacon is found inside Sester's Refuge, past the Abbey Entrance. Follow the main path through the refuge and continue up the stairs until you reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 31.348,
    y: 64.59,
    area: "World Map",
    region: null,
  },
  {
    id: "1565349",
    title: "Gate of Infinity",
    description: "This beacon can be accessed by heading straight up the stairs from Ruk, where you obtained the Map of Mammon (2). Follow the path to the end to reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 14.922,
    y: 47.945,
    area: "World Map",
    region: null,
  },
  {
    id: "1565350",
    title: "Castigator’s Keep",
    description: "This beacon is found at the top of the Castigator's Keep ruins. From the entrance, head right and follow the stone stairs up.",
    type: "beacon",
    classification: "Beacon",
    x: 29.219,
    y: 52.711,
    area: "World Map",
    region: null,
  },
  {
    id: "1565351",
    title: "Abbey Entrance",
    description: "This beacon is found past the Outskirts of Mammon Beacon. Cross the Bone Gate and follow through the ruins until you find Abbey Entrance.",
    type: "beacon",
    classification: "Beacon",
    x: 37.906,
    y: 59.613,
    area: "World Map",
    region: null,
  },
  {
    id: "1565352",
    title: "Abandoned Outpost",
    description: "This beacon is found south of the bone gate connecting the Outskirts of Mammon to the Deserted Slums. ",
    type: "beacon",
    classification: "Beacon",
    x: 40.059,
    y: 41.031,
    area: "World Map",
    region: null,
  },
  {
    id: "1565353",
    title: "Gate of Mammon",
    description: "This beacon is found on the southwestern tip of the map connected by a bone gate from the High Lord's Courtyard.",
    type: "beacon",
    classification: "Beacon",
    x: 30.812,
    y: 37.746,
    area: "World Map",
    region: null,
  },
  {
    id: "1565354",
    title: "The Silent Steps",
    description: "",
    type: "beacon",
    classification: "Beacon",
    x: 22.691,
    y: 55.613,
    area: "World Map",
    region: null,
  },
  {
    id: "1565355",
    title: "High Lord’s Courtyard",
    description: "This beacon is southwest of the Abandoned Outpost in the Ruins of Mammon. This is also near the location of a Map Fragment.",
    type: "beacon",
    classification: "Beacon",
    x: 35.594,
    y: 36.066,
    area: "World Map",
    region: null,
  },
  {
    id: "1565356",
    title: "Hangman’s Scaffold",
    description: "This beacon is found at the top of the castle walls. From the central courtyard, topple the stone statue by shooting the gas-filled pots, then use it as a ramp to reach the upper wall. Follow the stairs and exit through the archway to find the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 53.172,
    y: 31.945,
    area: "World Map",
    region: null,
  },
  {
    id: "1565357",
    title: "Executioner’s Pulpit",
    description: "This beacon is found above the Prisoner's Pulpit area. From the Hangman's Scaffold Beacon, take the wooden stairs and follow the path across the wooden bridges and up the stone stairs. Continue past the Resolve Stalk and drop down at the end to reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 53.105,
    y: 31.66,
    area: "World Map",
    region: null,
  },
  {
    id: "1565358",
    title: "Slumwater Drain",
    description: "This beacon is hidden inside a sewer grate in the first room of the Slumwater Drain. From the entrance, head right and look for the broken grate beside the torch.",
    type: "beacon",
    classification: "Beacon",
    x: 53.105,
    y: 31.445,
    area: "World Map",
    region: null,
  },
  {
    id: "1565359",
    title: "Captive’s End",
    description: "This beacon appears after defeating the Nameless Captive. Enter the beacon that rises after the boss fight to collect the Ova.",
    type: "beacon",
    classification: "Beacon",
    x: 53.098,
    y: 31.113,
    area: "World Map",
    region: null,
  },
  {
    id: "1565360",
    title: "Prisoner’s Domain",
    description: "",
    type: "gate",
    classification: "Gate",
    x: 53.277,
    y: 32.258,
    area: "World Map",
    region: null,
  },
  {
    id: "1565361",
    title: "Sanguine Caverns",
    description: "",
    type: "gate",
    classification: "Gate",
    x: 80.031,
    y: 48.504,
    area: "World Map",
    region: null,
  },
  {
    id: "1565362",
    title: "Pulsing Caves",
    description: "This beacon is found past the Pulsing Caves entrance. From the fork in the path, take the right path and follow it past the Lithopods to reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 80.281,
    y: 48.535,
    area: "World Map",
    region: null,
  },
  {
    id: "1565363",
    title: "Sanguine Shoreline",
    description: "This beacon is found inside the large cave past the two bridges. From the clearing, take the left bridge into the cave and follow the path until you reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 80.543,
    y: 48.551,
    area: "World Map",
    region: null,
  },
  {
    id: "1565364",
    title: "Child’s Feeding Grounds",
    description: "This beacon appears after defeating the Lost Child. Enter the beacon that rises from the ground to cleanse it.",
    type: "beacon",
    classification: "Beacon",
    x: 80.867,
    y: 48.535,
    area: "World Map",
    region: null,
  },
  {
    id: "1565365",
    title: "Conquered Temple",
    description: "",
    type: "gate",
    classification: "Gate",
    x: 31.016,
    y: 64.867,
    area: "World Map",
    region: null,
  },
  {
    id: "1565366",
    title: "Ovate’s Chamber",
    description: "This beacon is found at the top of the elevator leading to Droeg's arena. After defeating Urrig, use the Jumping Pad and follow the path upstairs to the elevator.",
    type: "beacon",
    classification: "Beacon",
    x: 30.723,
    y: 65.066,
    area: "World Map",
    region: null,
  },
  {
    id: "1565367",
    title: "Winterglass Lake",
    description: "This beacon is found at the bottom of the large multi-level structure in Conquered Temple. Exit the structure and descend the three flights of stairs to reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 30.453,
    y: 65.301,
    area: "World Map",
    region: null,
  },
  {
    id: "1565368",
    title: "Conqueror’s Hoard",
    description: "This beacon is found after defeating Droeg, The Conquerer. Once Droeg is defeated, the Conqueror's Hoard emerges from the ground.",
    type: "beacon",
    classification: "Beacon",
    x: 30.242,
    y: 65.449,
    area: "World Map",
    region: null,
  },
  {
    id: "1565369",
    title: "Faded Citadel",
    description: "",
    type: "gate",
    classification: "Gate",
    x: 14.34,
    y: 47.723,
    area: "World Map",
    region: null,
  },
  {
    id: "1565370",
    title: "Citadel Annex",
    description: "This beacon is found on a balcony past an egg-filled cave. Head up through the cave and climb the stairs on the other side until you reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 14.051,
    y: 47.703,
    area: "World Map",
    region: null,
  },
  {
    id: "1565371",
    title: "Citadel Atrium",
    description: "This beacon is found on the lower level of the room past the chained platform. From Solnir boss arena, take the elevator, use the Bone Gate to cross the gap, head left where you'll see a Canyon Crawler, and walk all the way down until you reach the beacon.",
    type: "beacon",
    classification: "Beacon",
    x: 13.762,
    y: 47.555,
    area: "World Map",
    region: null,
  },
  {
    id: "1565372",
    title: "Scholar-Prince’s Chamber",
    description: "This beacon is found inside Sir Isaac, the Scholar-Prince boss arena.",
    type: "beacon",
    classification: "Beacon",
    x: 13.383,
    y: 47.438,
    area: "World Map",
    region: null,
  },
  {
    id: "1565373",
    title: "Withered Shoals",
    description: "",
    type: "gate",
    classification: "Gate",
    x: 30.559,
    y: 37.496,
    area: "World Map",
    region: null,
  },
  {
    id: "1565374",
    title: "Nameless Pass",
    description: "This beacon is found past the Cefatropod cave following the rocky ramp shortcut.",
    type: "beacon",
    classification: "Beacon",
    x: 30.375,
    y: 37.285,
    area: "World Map",
    region: null,
  },
  {
    id: "1565375",
    title: "Ossinite Falls",
    description: "This beacon is found just past the rocky hill after the room with the Grisha Hunters.",
    type: "beacon",
    classification: "Beacon",
    x: 30.164,
    y: 37.125,
    area: "World Map",
    region: null,
  },
  {
    id: "1565376",
    title: "Hexapod’s Burrow",
    description: "This beacon is found hidden in the mist inside the Hexapod boss arena.",
    type: "beacon",
    classification: "Beacon",
    x: 29.977,
    y: 36.883,
    area: "World Map",
    region: null,
  },
  {
    id: "1565385",
    title: "Disciple’s Grotto",
    description: "This is the second beacon you will activate during the Prologue.",
    type: "beacon",
    classification: "Beacon",
    x: 48.398,
    y: 19.914,
    area: "World Map",
    region: null,
  },
  {
    id: "1565386",
    title: "Village Outskirts",
    description: "This is the first beacon you will activate during the Prologue.",
    type: "beacon",
    classification: "Beacon",
    x: 48.125,
    y: 19.93,
    area: "World Map",
    region: null,
  },
  {
    id: "1565389",
    title: "Shattering Stone",
    description: "The Shattering Stone is found in a chest located inside the Collapsed Mine dungeon. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 35.801,
    y: 41.891,
    area: "World Map",
    region: null,
  },
  {
    id: "1565390",
    title: "Shrike Stone",
    description: "The Shrike Stone is found in a chest  within the Glutten Mire. In the wide area just before the Sunken Village beacon, find the alternate path leading to a wide area with a chest at the end.",
    type: "tarstone",
    classification: "Tarstone",
    x: 60.867,
    y: 62.141,
    area: "World Map",
    region: null,
  },
  {
    id: "1565391",
    title: "Barrage Stone",
    description: "The Barrage Stone is obtained as a reward for completing the trials of the Corrupted Statue found in the Gloomshade Grove.",
    type: "tarstone",
    classification: "Tarstone",
    x: 69.535,
    y: 45.066,
    area: "World Map",
    region: null,
  },
  {
    id: "1565393",
    title: "Shattered Beacon",
    description: "This beacon can be found north of the Blackridge Pass beacon guarded by an Infested Stalker.",
    type: "dungeon",
    classification: "Dungeon",
    x: 71.703,
    y: 51.871,
    area: "World Map",
    region: null,
  },
  {
    id: "1565397",
    title: "Overrun Quarry",
    description: "This dungeon can be found just north of the One-Legged Wolf beacon. ",
    type: "dungeon",
    classification: "Dungeon",
    x: 67.41,
    y: 62.672,
    area: "World Map",
    region: null,
  },
  {
    id: "1565398",
    title: "Hall of Echoes",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 70.969,
    y: 57.832,
    area: "World Map",
    region: null,
  },
  {
    id: "1565399",
    title: "Feeding Grounds",
    description: "This dungeon is unlocked by breaking three Golden Flower Tombstones at the Stones of Remembrance.",
    type: "dungeon",
    classification: "Dungeon",
    x: 74.367,
    y: 57.645,
    area: "World Map",
    region: null,
  },
  {
    id: "1565400",
    title: "Crumbling Tunnel",
    description: "This dungeon is found directly across from the Shattered Beacon dungeon where you can pick up Proxima's shell.",
    type: "dungeon",
    classification: "Dungeon",
    x: 71.812,
    y: 52.586,
    area: "World Map",
    region: null,
  },
  {
    id: "1565401",
    title: "The King’s Crypt",
    description: "This dungeon is found north of the Blackridge Pass beacon, past the Shattered Beacon dungeon. ",
    type: "dungeon",
    classification: "Dungeon",
    x: 73.125,
    y: 50.285,
    area: "World Map",
    region: null,
  },
  {
    id: "1565402",
    title: "Ravaged Hideout",
    description: "This dungeon is found southeast of the Gloomshade Grove beacon. Its entrance is guarded by the Bloodcursed Lithopod.",
    type: "dungeon",
    classification: "Dungeon",
    x: 68.039,
    y: 43.773,
    area: "World Map",
    region: null,
  },
  {
    id: "1565403",
    title: "Holding Cells",
    description: "This dungeon is accessible once you defeat the Bloodcursed Lithopod boss guarding its entrance.",
    type: "dungeon",
    classification: "Dungeon",
    x: 72.453,
    y: 40.156,
    area: "World Map",
    region: null,
  },
  {
    id: "1565404",
    title: "Martyr’s Prison",
    description: "This dungeon is found to be located northwest of Gloomshade Grove Beacon. Northeast of the castle's outskirts",
    type: "dungeon",
    classification: "Dungeon",
    x: 73.074,
    y: 39.117,
    area: "World Map",
    region: null,
  },
  {
    id: "1565405",
    title: "Illusionist’s Cache",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 63.602,
    y: 35.934,
    area: "World Map",
    region: null,
  },
  {
    id: "1565406",
    title: "Thieves Retreat",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 55.41,
    y: 33.367,
    area: "World Map",
    region: null,
  },
  {
    id: "1565407",
    title: "Ravaged Tomb",
    description: "This dungeon is found directly below the Nochtean Gate beacon on the lower grounds of the ruins.",
    type: "dungeon",
    classification: "Dungeon",
    x: 52.754,
    y: 33.188,
    area: "World Map",
    region: null,
  },
  {
    id: "1565408",
    title: "Desolate Keep",
    description: "This dungeon located directly across from Sester Genessa in Marrow Keep. Reveal an Illusionary Wall for the dungeon entrance.",
    type: "dungeon",
    classification: "Dungeon",
    x: 49.73,
    y: 46.469,
    area: "World Map",
    region: null,
  },
  {
    id: "1565409",
    title: "Smuggler’s Hideout",
    description: "This dungeon can be found to the east of the Outskirts of Mammon beacon.",
    type: "dungeon",
    classification: "Dungeon",
    x: 43.918,
    y: 47.891,
    area: "World Map",
    region: null,
  },
  {
    id: "1565410",
    title: "Hag’s Pit",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 42.312,
    y: 51.762,
    area: "World Map",
    region: null,
  },
  {
    id: "1565411",
    title: "Bellkeeper’s Corner",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 41.508,
    y: 41.363,
    area: "World Map",
    region: null,
  },
  {
    id: "1565412",
    title: "Revenant Graves",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 39.117,
    y: 57.695,
    area: "World Map",
    region: null,
  },
  {
    id: "1565413",
    title: "Besieged Ruins",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 36.105,
    y: 38.352,
    area: "World Map",
    region: null,
  },
  {
    id: "1565414",
    title: "Collapsed Mine",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 35.93,
    y: 41.922,
    area: "World Map",
    region: null,
  },
  {
    id: "1565415",
    title: "Obsidianite Mines",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 36.133,
    y: 43.348,
    area: "World Map",
    region: null,
  },
  {
    id: "1565416",
    title: "Revered Dungeon",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 35.023,
    y: 61.523,
    area: "World Map",
    region: null,
  },
  {
    id: "1565417",
    title: "Spoiled Mortuary",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 32.336,
    y: 39.82,
    area: "World Map",
    region: null,
  },
  {
    id: "1565418",
    title: "Sentry’s Grave",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 31.973,
    y: 41.207,
    area: "World Map",
    region: null,
  },
  {
    id: "1565419",
    title: "Blackwell Cavern",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 31.332,
    y: 53.262,
    area: "World Map",
    region: null,
  },
  {
    id: "1565420",
    title: "Hall of Murmurs",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 24.969,
    y: 51.219,
    area: "World Map",
    region: null,
  },
  {
    id: "1565421",
    title: "Parasitic Stash",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 24.543,
    y: 58.621,
    area: "World Map",
    region: null,
  },
  {
    id: "1565422",
    title: "Chamber of Becoming",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 17.418,
    y: 59.484,
    area: "World Map",
    region: null,
  },
  {
    id: "1565429",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 59.496,
    y: 48.543,
    area: "World Map",
    region: null,
  },
  {
    id: "1565430",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 64.891,
    y: 70.516,
    area: "World Map",
    region: null,
  },
  {
    id: "1565431",
    title: "Veteran’s Battle Axe",
    description: "The Veteran's Battle Axe is located on the lowest level of the King's Crypt and is guarded by a Tough Brigand.",
    type: "weapon",
    classification: "Weapon",
    x: 73.199,
    y: 50.168,
    area: "World Map",
    region: null,
  },
  {
    id: "1565432",
    title: "Salvaged Trebuchaxe",
    description: "Find the crevice at the end of the Ravaged Hideout and obtain the Salvaged Trebuchaxe from the kneeling corpse. Be careful, as enemies will ambush you from behind as you approach the corpse.",
    type: "sidearm",
    classification: "Sidearm",
    x: 67.906,
    y: 43.84,
    area: "World Map",
    region: null,
  },
  {
    id: "1565433",
    title: "Ballistazooka",
    description: "Head to Sentry's Grave, then make your way to the boss's room and defeat the Subjugated Guardian to obtain the Ballistazooka.",
    type: "sidearm",
    classification: "Sidearm",
    x: 31.812,
    y: 41.176,
    area: "World Map",
    region: null,
  },
  {
    id: "1565434",
    title: "Cursed Child",
    description: "Make your way to the flashing light in the middle of the Revered Beacon and attack it to reveal and obtain the Cursed Child.",
    type: "sidearm",
    classification: "Sidearm",
    x: 35.086,
    y: 61.687,
    area: "World Map",
    region: null,
  },
  {
    id: "1565435",
    title: "Triarch Repeater",
    description: "Proceed through the cavern until you reach an area with a broken wagon and the corpses of a human and a horse. The Triarch Repeater can be found on the ground in this area.",
    type: "sidearm",
    classification: "Sidearm",
    x: 31.285,
    y: 53.375,
    area: "World Map",
    region: null,
  },
  {
    id: "1565436",
    title: "Caged Hystrix",
    description: "Head to the Chamber of Becoming dungeon and defeat Sariel, the Endless. Then, climb the stairs past the boss arena and obtain the Caged Hystrix from the top.",
    type: "sidearm",
    classification: "Sidearm",
    x: 17.324,
    y: 59.684,
    area: "World Map",
    region: null,
  },
  {
    id: "1565437",
    title: "Axatana",
    description: "To get the Axatana, go to the teleporter in the eastern part of the map that leads to the Forgotten Tower. Keep going up the stairs and press the plate to open the gate. Defeat the Gloom Seeker in the room and take the Axatana near the candles. ",
    type: "weapon",
    classification: "Weapon",
    x: 28.398,
    y: 63.199,
    area: "World Map",
    region: null,
  },
  {
    id: "1565438",
    title: "Obsidian Hammer",
    description: "To obtain the Obsidian Hammer, teleport to the Gate of Mammon beacon and head to the collapsed mine. Make your way through the mine and take the elevator to the Deserted Slums. Continue through the slums to reach the Obsidianite Mines. Go to the lowest level and defeat the Prophet of Profane Infinities to get the Obsidian Hammer. ",
    type: "weapon",
    classification: "Weapon",
    x: 35.957,
    y: 42.074,
    area: "World Map",
    region: null,
  },
  {
    id: "1565439",
    title: "Clockwork Scythe",
    description: "To get the Clockwerk Scythe, head to the Chamber of Becoming dungeon, which is located in the southern part of the map. Defeat Sariel, the Endless, and you'll be able to get the Clockwerk Scythe upon his defeat.",
    type: "weapon",
    classification: "Weapon",
    x: 17.426,
    y: 59.637,
    area: "World Map",
    region: null,
  },
  {
    id: "1565440",
    title: "Black Needle",
    description: "Defeat the Stray Sesters in the Sester's Gate beacon to obtain the Black Needle.",
    type: "weapon",
    classification: "Weapon",
    x: 31.242,
    y: 64.586,
    area: "World Map",
    region: null,
  },
  {
    id: "1565441",
    title: "Great Martyr’s Blade",
    description: "The Great Martyr's Blade is inside Martyr's Prison, in a room blocked by a box.",
    type: "weapon",
    classification: "Weapon",
    x: 73.246,
    y: 39.129,
    area: "World Map",
    region: null,
  },
  {
    id: "1565442",
    title: "Naylshotte",
    description: "The Naylshotte is provided as part of the introductory tutorial.",
    type: "sidearm",
    classification: "Sidearm",
    x: 48.426,
    y: 22.016,
    area: "World Map",
    region: null,
  },
  {
    id: "1565443",
    title: "The Iconoclast",
    description: "The Iconoclast is provided as part of the introductory tutorial.",
    type: "weapon",
    classification: "Weapon",
    x: 48.25,
    y: 21.82,
    area: "World Map",
    region: null,
  },
  {
    id: "1565444",
    title: "Lazlo, The Justicar",
    description: "To obtain Lazlo, head to the Royal Crypt of Mammon, which is located in the southwest area of the map. Defeat Vellen, the High Lord of Mammon, and continue through the dungeon until you reach the crypts. Follow the torch-lit path to find Lazlo's shell, which you can obtain after playing through his memory.",
    type: "shell",
    classification: "Shell",
    x: 34.93,
    y: 33.543,
    area: "World Map",
    region: null,
  },
  {
    id: "1565445",
    title: "Sariel, The Endless",
    description: "To get Sariel, head to the Chamber of Becoming dungeon, which is located in the southern part of the map. Defeat Sariel, the Endless. You will then be able to interact with his corpse, play out his memory, and obtain the shell.",
    type: "shell",
    classification: "Shell",
    x: 17.227,
    y: 59.668,
    area: "World Map",
    region: null,
  },
  {
    id: "1565446",
    title: "Smert, The Apostate",
    description: "To get Smert, start by head into Prophet's Rest and interacting with the middle circle to trigger the Blood Offering, which will cause you to lose your shell. Use the enemies scattered around the area to regain your shell, then do the same with the circle on the right. Once all blood offerings are glowing red, interact with Smert's corpse to view his memory and obtain it.",
    type: "shell",
    classification: "Shell",
    x: 57.176,
    y: 35.383,
    area: "World Map",
    region: null,
  },
  {
    id: "1566495",
    title: "Justiciar’s Stone",
    description: "The Justiciar's Stone can be found on a shrine near where a swarm of Broodshell Snails will attack you. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 72.98,
    y: 59.57,
    area: "World Map",
    region: null,
  },
  {
    id: "1566496",
    title: "Gloombound Stone",
    description: "The Gloombound Stone can be found in a chest in the Stones of Remembrance.",
    type: "tarstone",
    classification: "Tarstone",
    x: 73.203,
    y: 55.324,
    area: "World Map",
    region: null,
  },
  {
    id: "1566497",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 74.344,
    y: 52.137,
    area: "World Map",
    region: null,
  },
  {
    id: "1566498",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 74.281,
    y: 51.363,
    area: "World Map",
    region: null,
  },
  {
    id: "1566499",
    title: "Corrupted Statue - Gloomshade Grove",
    description: "This corrupted statue can be found past the Blackridge Pass beacon as you make your way to the west.  ",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 69.789,
    y: 45.008,
    area: "World Map",
    region: null,
  },
  {
    id: "1566536",
    title: "Fulminant Stone",
    description: "This Fulminant Stone can only be bought from the Night Merchant, an NPC that only appears when you are in Night mode. Accessing Night mode requires the Gloombound Flame from the Great Arbiter of Flesh boss area.",
    type: "tarstone",
    classification: "Tarstone",
    x: 38.988,
    y: 41.66,
    area: "World Map",
    region: null,
  },
  {
    id: "1566537",
    title: "Infested Stone",
    description: "The Infested Stone can only be bought from the Night Merchant, an NPC that only appears when you are in Night mode. Accessing Night mode requires the Gloombound Flame from the Great Arbiter of Flesh boss area.",
    type: "tarstone",
    classification: "Tarstone",
    x: 38.98,
    y: 41.723,
    area: "World Map",
    region: null,
  },
  {
    id: "1566538",
    title: "Weeping Stone",
    description: "The Weeping Stone can only be bought from the Night Merchant, an NPC that only appears when you are in Night mode. Accessing Night mode requires the Gloombound Flame from the Great Arbiter of Flesh boss area.",
    type: "tarstone",
    classification: "Tarstone",
    x: 38.77,
    y: 41.629,
    area: "World Map",
    region: null,
  },
  {
    id: "1566539",
    title: "Infused Stone",
    description: "The Infused Stone can only be bought from the Night Merchant, an NPC that only appears when you are in Night mode. Accessing Night mode requires the Gloombound Flame from the Great Arbiter of Flesh boss area.",
    type: "tarstone",
    classification: "Tarstone",
    x: 38.953,
    y: 41.77,
    area: "World Map",
    region: null,
  },
  {
    id: "1566540",
    title: "Clerik’s Stone",
    description: "The Clerik's Stone is found in a chest behind a secret hidden wall in the Ruins of Nochte. This chest will be near a cliff's edge. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 58.73,
    y: 39.332,
    area: "World Map",
    region: null,
  },
  {
    id: "1566541",
    title: "Tyrant’s Stone",
    description: "The Tyrant's Stone is found in a chest behind a secret hidden wall in the Sester's Abbey.",
    type: "tarstone",
    classification: "Tarstone",
    x: 41.105,
    y: 58.355,
    area: "World Map",
    region: null,
  },
  {
    id: "1566542",
    title: "Map of Mammon【5】",
    description: "This map fragment can be found just south west of the Outskirts of Mammon beacon. ",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 41.375,
    y: 46.281,
    area: "World Map",
    region: null,
  },
  {
    id: "1566543",
    title: "Colossus Stone",
    description: "The Colossus Stone is found in a chest in the Silent Steps, north of the Parasitic Stash dungeon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 27.871,
    y: 57.504,
    area: "World Map",
    region: null,
  },
  {
    id: "1566544",
    title: "Warden’s Stone",
    description: "The Warden's Stone is obtained as a reward for defeating Urrig the Executioner, a boss near the Winterglass Lake beacon in the Conquered Temple Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.398,
    y: 65.203,
    area: "World Map",
    region: null,
  },
  {
    id: "1566545",
    title: "Serpent Stone",
    description: "The Serpent Stone is obtained as a reward for defeating Lucian the Thirsting Knight in the Stonebled Gate beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 79.789,
    y: 48.469,
    area: "World Map",
    region: null,
  },
  {
    id: "1566546",
    title: "Blackblood Stone",
    description: "The Blackblood Stone is obtained inside the Mawbreak Cavern, a dungeon found when you cleanse the Pulsing Caves beacon in the Sanguine Caverns Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 80.336,
    y: 48.453,
    area: "World Map",
    region: null,
  },
  {
    id: "1566547",
    title: "Bulwark Stone",
    description: "The Bulwark Stone can be found in a chest located at the end of a broken bridge at the south end of the Citadel of Penance.",
    type: "tarstone",
    classification: "Tarstone",
    x: 64.867,
    y: 38.59,
    area: "World Map",
    region: null,
  },
  {
    id: "1566548",
    title: "Confessor’s Keepsake",
    description: "The Confessor's Keepsake is obtained as a reward for defeating Tishina's Confessor just before reaching the Executioner's Pulpit beacon inside the Prisoner's Domain gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 53.172,
    y: 31.82,
    area: "World Map",
    region: null,
  },
  {
    id: "1566549",
    title: "Captive’s Scabstone",
    description: "The Captive's Scabstone is obtain after defeating the Nameless Captive boss inside the Prisoner's domain.",
    type: "tarstone",
    classification: "Tarstone",
    x: 53.008,
    y: 31.262,
    area: "World Map",
    region: null,
  },
  {
    id: "1566550",
    title: "Rupturing Stone",
    description: "The Rupturing Stone is found inside a chest just above the boss area where you fight the Nameless Captive in the Prisoner's Domain.",
    type: "tarstone",
    classification: "Tarstone",
    x: 53.145,
    y: 31.32,
    area: "World Map",
    region: null,
  },
  {
    id: "1566551",
    title: "Curseblood Stone",
    description: "The Curseblood Stone is obtained as a reward for defeating the Gloombound Wraith, a boss in the Forbidden Archives, the dungeon within the Gate of Infinity beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 14.895,
    y: 47.863,
    area: "World Map",
    region: null,
  },
  {
    id: "1566552",
    title: "Map of Mammon【6】",
    description: "This map fragment can be found right across from the High Lord's Courtyard beacon.",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 36.137,
    y: 36.746,
    area: "World Map",
    region: null,
  },
  {
    id: "1566553",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 40.117,
    y: 45.055,
    area: "World Map",
    region: null,
  },
  {
    id: "1566554",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 40.418,
    y: 41.805,
    area: "World Map",
    region: null,
  },
  {
    id: "1566555",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 39.805,
    y: 40.223,
    area: "World Map",
    region: null,
  },
  {
    id: "1566556",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 37.875,
    y: 39.184,
    area: "World Map",
    region: null,
  },
  {
    id: "1566557",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 33.461,
    y: 37.09,
    area: "World Map",
    region: null,
  },
  {
    id: "1566558",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 32.531,
    y: 38.047,
    area: "World Map",
    region: null,
  },
  {
    id: "1566559",
    title: "Voltaic Amber",
    description: "The Voltaic Amber is obtained as a reward for defeating the Starved Harridan boss at the Vestige of Infinity, south of the Castigator's Keep beacon. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 23.367,
    y: 51.113,
    area: "World Map",
    region: null,
  },
  {
    id: "1566567",
    title: "Map of Fainweald【1】",
    description: "This map fragment is found just north of the Outskirts of Nochte beacon in The Hag's Path",
    type: "mapFragment",
    classification: "Map Fragment",
    x: 60.504,
    y: 38.914,
    area: "World Map",
    region: null,
  },
  {
    id: "1566568",
    title: "Hag Stone",
    description: "The Hag Stone is found in a chest at the end of the Infested Den, a dungeon inside the Outskirts of Nochte beacon accessible when you enter the beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 58.734,
    y: 37.832,
    area: "World Map",
    region: null,
  },
  {
    id: "1566569",
    title: "Duality Stone",
    description: "The Duality Stone is found in a chest at the end of the Ravaged Tomb dungeon in the Ruins of Nochte.",
    type: "tarstone",
    classification: "Tarstone",
    x: 52.633,
    y: 33.102,
    area: "World Map",
    region: null,
  },
  {
    id: "1566570",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 61.945,
    y: 45.277,
    area: "World Map",
    region: null,
  },
  {
    id: "1566571",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 59.0,
    y: 35.93,
    area: "World Map",
    region: null,
  },
  {
    id: "1566572",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 61.277,
    y: 35.215,
    area: "World Map",
    region: null,
  },
  {
    id: "1566573",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 54.504,
    y: 36.605,
    area: "World Map",
    region: null,
  },
  {
    id: "1566596",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 53.652,
    y: 37.133,
    area: "World Map",
    region: null,
  },
  {
    id: "1566597",
    title: "Voltaic Crown",
    description: "The Voltaic Crown is obtained as a reward for defeating Vrago, Solikar Champion, the boss of the Nochtean Gate beacon when you cleanse it.",
    type: "tarstone",
    classification: "Tarstone",
    x: 53.379,
    y: 32.414,
    area: "World Map",
    region: null,
  },
  {
    id: "1566598",
    title: "Alchemist’s Workshop",
    description: "",
    type: "dungeon",
    classification: "Dungeon",
    x: 26.895,
    y: 47.551,
    area: "World Map",
    region: null,
  },
  {
    id: "1566599",
    title: "Clockwork Shardstone",
    description: "The Clockwork Shardstone is found in a chest at the very end of the Alchemist's Workshop dungeon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 26.895,
    y: 47.461,
    area: "World Map",
    region: null,
  },
  {
    id: "1566829",
    title: "Enfeebling Stone",
    description: "The Enfeebling Stone is obtained as a reward for completing the combat trial of the Corrupted Statue in the Outskirts of Mammon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 42.633,
    y: 51.641,
    area: "World Map",
    region: null,
  },
  {
    id: "1566830",
    title: "Corrupted Statue - Outskirts of Mammon",
    description: "This statue is found just east of the Outskirts of Mammon beacon, above the Hag's Pit dungeon. ",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 42.738,
    y: 51.594,
    area: "World Map",
    region: null,
  },
  {
    id: "1566835",
    title: "Gloombound Flame",
    description: "This candle can be found on a pillar near where the Great Arbiter of Flesh boss area in Widow's Overlook. ",
    type: "keyItem",
    classification: "Key Item",
    x: 62.098,
    y: 51.48,
    area: "World Map",
    region: null,
  },
  {
    id: "1566868",
    title: "Hand of Rock",
    description: "The Hand of Rock can be bought from the Barkeep at the One-Legged Wolf Tavern.",
    type: "tarstone",
    classification: "Tarstone",
    x: 63.816,
    y: 63.859,
    area: "World Map",
    region: null,
  },
  {
    id: "1566869",
    title: "Citadel Gate Lever",
    description: "This item drops from the Bloodcursed Lithopod, a boss that hides in front of the Ravaged Hideout dungeon.",
    type: "keyItem",
    classification: "Key Item",
    x: 67.84,
    y: 43.762,
    area: "World Map",
    region: null,
  },
  {
    id: "1566871",
    title: "Crypt Key",
    description: "This item can be found within the Desolate Peak. Look inside the dungeon entrance, the key will be on top of a table.",
    type: "keyItem",
    classification: "Key Item",
    x: 63.668,
    y: 35.859,
    area: "World Map",
    region: null,
  },
  {
    id: "1566872",
    title: "Deadeye Stone",
    description: "The Deadeye Stone can be found by opening a chest surrounded by Brigands in the Sanguine Caverns.",
    type: "tarstone",
    classification: "Tarstone",
    x: 80.281,
    y: 48.789,
    area: "World Map",
    region: null,
  },
  {
    id: "1566873",
    title: "Special Moonshine",
    description: "You can get this item from a crate across from Baghead in the Desolate Peak just by the entrance to the dungeon.",
    type: "keyItem",
    classification: "Key Item",
    x: 63.406,
    y: 36.18,
    area: "World Map",
    region: null,
  },
  {
    id: "1566874",
    title: "Ironpiercer’s Stone",
    description: "The Ironpiercer's Stone is found in a chest located in the upper levels of the Central Sewers dungeon near the Executioner's Pulpit beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 53.25,
    y: 31.598,
    area: "World Map",
    region: null,
  },
  {
    id: "1566875",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 64.035,
    y: 36.703,
    area: "World Map",
    region: null,
  },
  {
    id: "1566876",
    title: "Bone Gate",
    description: "",
    type: "collectible",
    classification: "Bone Gate",
    x: 66.168,
    y: 37.637,
    area: "World Map",
    region: null,
  },
  {
    id: "1566995",
    title: "Poisoned Dagger",
    description: "The Poisoned Dagger is given by Gorf after you help him by giving him Weltcaps. This dagger is to be given to Hilga near the Mushroom Village Beacon.",
    type: "keyItem",
    classification: "Key Item",
    x: 67.027,
    y: 50.473,
    area: "World Map",
    region: null,
  },
  {
    id: "1567130",
    title: "Lost Clotstone",
    description: "The Lost Clotstone is obtained as a reward for defeatingThe Lost Child, the final boss of the Sanguine Caverns Gate, found in the Child's Feeding Grounds.",
    type: "tarstone",
    classification: "Tarstone",
    x: 80.836,
    y: 48.398,
    area: "World Map",
    region: null,
  },
  {
    id: "1567131",
    title: "Tarred Fragment",
    description: "The Tarred Fragment is obtained as a reward for defeating the Tarblighted Stoner, the boss of the Sanguine Caverns Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 80.691,
    y: 48.605,
    area: "World Map",
    region: null,
  },
  {
    id: "1567132",
    title: "Myriad Stone",
    description: "The Myriad Stone  is found in a chest in the Feeding Grounds dungeon. First find the Crypt Key  in The Desolate Peak to access this dungeon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 74.473,
    y: 57.832,
    area: "World Map",
    region: null,
  },
  {
    id: "1567133",
    title: "Scholar’s Wormstone",
    description: "The Scholar's Wormstone is obtained as a reward for defeat Sir Isaac, the Scholar-Prince, the final boss of the Faded Citadel Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 13.496,
    y: 47.379,
    area: "World Map",
    region: null,
  },
  {
    id: "1567134",
    title: "Accursed Stone",
    description: "The Accursed Stone is obtained from a chest found inside the Abandoned Outpost when you cleanse the beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 40.02,
    y: 40.949,
    area: "World Map",
    region: null,
  },
  {
    id: "1567135",
    title: "Charged Stone",
    description: "The Charged Stone is obtained from a chest in the Nameless Pass beacon when you cleanse it.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.328,
    y: 37.445,
    area: "World Map",
    region: null,
  },
  {
    id: "1567136",
    title: "Conquerer’s Reward",
    description: "The Conqueror's Reward is obtained as a reward for defeating Droeg, the Conqueror, the final boss of the Conquered Temple Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.215,
    y: 65.379,
    area: "World Map",
    region: null,
  },
  {
    id: "1567137",
    title: "Devout Stone",
    description: "The Devout Stone is found in a chest located in the Sester's Refuge.",
    type: "tarstone",
    classification: "Tarstone",
    x: 33.715,
    y: 64.293,
    area: "World Map",
    region: null,
  },
  {
    id: "1567138",
    title: "Frostshard Stone",
    description: "The Frostshard Stone can be obtained from a chest located at the very end of the Conqueror's Hoard beacon when you cleanse it. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.41,
    y: 65.465,
    area: "World Map",
    region: null,
  },
  {
    id: "1567139",
    title: "Fusillade Stone",
    description: "The Fusillade Stone can be obtained as a reward for defeating the Caged Grisha boss inside the Winterglass Lake beacon in the Conquered Temple Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.402,
    y: 65.406,
    area: "World Map",
    region: null,
  },
  {
    id: "1567140",
    title: "Headman’s Stone",
    description: "The Headman's Stone is found in a chest in the Outskirts of Mammon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 38.707,
    y: 51.742,
    area: "World Map",
    region: null,
  },
  {
    id: "1567141",
    title: "Hexapod Core",
    description: "The Hexapod Core is obtained as a reward for defeating the Hexapod, the final boss of the Withered Shoals Gate, in the Hexapod's Burrow. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.031,
    y: 36.793,
    area: "World Map",
    region: null,
  },
  {
    id: "1567142",
    title: "Inflamed Clawstone",
    description: "The Inflamed Clawstone is obtained as a reward for defeating the Rabid Grisha Pack, a dungeon boss of the Holding Cells.",
    type: "tarstone",
    classification: "Tarstone",
    x: 72.68,
    y: 40.324,
    area: "World Map",
    region: null,
  },
  {
    id: "1567143",
    title: "Monarch’s Vestige",
    description: "The Monarch's Vestige is obtained as  a reward for defeating Bor the Deluded Monarch inside the Abbey Entrance beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 37.918,
    y: 59.797,
    area: "World Map",
    region: null,
  },
  {
    id: "1567144",
    title: "Nightgrasp Stone",
    description: "The Nightgrasp Stone is obtained from a chest found near the Abbey Entrance beacon. The chest will only open after three offerings have been made by lighting the candles in the area.",
    type: "tarstone",
    classification: "Tarstone",
    x: 32.957,
    y: 57.469,
    area: "World Map",
    region: null,
  },
  {
    id: "1567145",
    title: "Pulse Stone",
    description: "The Pulse Stone can be obtained from chest located near the Winterglass Lake beacon inside the Conquered Temple Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.613,
    y: 65.359,
    area: "World Map",
    region: null,
  },
  {
    id: "1567146",
    title: "Shuddering Stone",
    description: "The Shuddering Stone can be found in a chest inside the Illusionist's Cache, a dungeon in The Desolate Peak.",
    type: "tarstone",
    classification: "Tarstone",
    x: 63.742,
    y: 35.801,
    area: "World Map",
    region: null,
  },
  {
    id: "1567147",
    title: "Solnir Shard",
    description: "The Solnir Shard can be obtained as a reward for defeating Solnir the Gloomseeker, a boss found when you cleanse the Citadel Annex beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 13.992,
    y: 47.602,
    area: "World Map",
    region: null,
  },
  {
    id: "1567148",
    title: "Spite Stone",
    description: "The Spite Stone is obtained from a chest found inside the Bellkeeper's Corner dungeon near the Abandoned Outpost beacon.  ",
    type: "tarstone",
    classification: "Tarstone",
    x: 41.637,
    y: 41.379,
    area: "World Map",
    region: null,
  },
  {
    id: "1567149",
    title: "Splitting Stone",
    description: "The Splitting Stone can be obtained from a chest in the Lonesome Spire, the building found on the east of the Gate of Mammon beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 31.879,
    y: 42.867,
    area: "World Map",
    region: null,
  },
  {
    id: "1567150",
    title: "Squall Stone",
    description: "The Squall Stone is obtained from a chest found inside the Executioner's Pulpit beacon inside the Prisoner's Domain Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 52.98,
    y: 31.656,
    area: "World Map",
    region: null,
  },
  {
    id: "1567151",
    title: "Stillblade’s Stone",
    description: "The Stillblade's Stone can be looted from a chest found inside the Citadel Annex beacon when you cleanse it.",
    type: "tarstone",
    classification: "Tarstone",
    x: 13.898,
    y: 47.754,
    area: "World Map",
    region: null,
  },
  {
    id: "1567152",
    title: "Strange Remnant",
    description: "The Strange Remnant can be obtained as a reward for defeating the Strange Grisha in the Withered Shoals Gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.402,
    y: 37.504,
    area: "World Map",
    region: null,
  },
  {
    id: "1567153",
    title: "Summoning Stone",
    description: "The Summonning Stone can be looted from a chest in the Ashen Sanctum, an area you can access when you enter the Faded Citadel gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 13.938,
    y: 47.551,
    area: "World Map",
    region: null,
  },
  {
    id: "1567154",
    title: "Thief’s Stone",
    description: "The Thief's Stone is obtained as a reward for clearing the Corrupted Statue in the Vestige of Infinity.",
    type: "tarstone",
    classification: "Tarstone",
    x: 20.223,
    y: 51.043,
    area: "World Map",
    region: null,
  },
  {
    id: "1567155",
    title: "Torpor Stone",
    description: "The Torpor Stone can be looted from a chest found near the Ossinite Falls beacon in the Withered Shoals gate.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.02,
    y: 37.172,
    area: "World Map",
    region: null,
  },
  {
    id: "1567156",
    title: "Unstable Stone",
    description: "The Unstable Stone can be looted from a chest located west of the Castigator's Keep beacon.",
    type: "tarstone",
    classification: "Tarstone",
    x: 28.504,
    y: 48.68,
    area: "World Map",
    region: null,
  },
  {
    id: "1567157",
    title: "Viletongue Hedron",
    description: "The Viletongue Hedron can be obtained as a reward for defeating the Viletongue Batushka, the boss at the end of the Castigator's Keep when you cleanse it. ",
    type: "tarstone",
    classification: "Tarstone",
    x: 29.156,
    y: 52.637,
    area: "World Map",
    region: null,
  },
  {
    id: "1567158",
    title: "Wretchcaller’s Stone",
    description: "The Wretchcaller's Stone is obtained as a reward for defeating the Infested Miner, a boss found at the end of the Gate of Mammon beacon when you cleanse it.",
    type: "tarstone",
    classification: "Tarstone",
    x: 30.691,
    y: 37.789,
    area: "World Map",
    region: null,
  },
  {
    id: "1567159",
    title: "Zealot’s Stone",
    description: "The Zealot's Stone is obtained as a reward for clearing the Besieged Ruins dungeon found to the east of the High Lord's Courtyard.",
    type: "tarstone",
    classification: "Tarstone",
    x: 36.195,
    y: 38.258,
    area: "World Map",
    region: null,
  },
  {
    id: "1567160",
    title: "Corrupted Statue - Vestige of Infinity",
    description: "This corrupted statue is found in the Vestige of Infinity in the southernmost region of the world map. ",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 20.168,
    y: 50.941,
    area: "World Map",
    region: null,
  },
  {
    id: "1567226",
    title: "Corrupted Statue - Revenant Graves",
    description: "This corrupted stateue can be found on the northeast tower of the Revenant Graves.",
    type: "corruptedStatue",
    classification: "Corrupted Statue",
    x: 34.367,
    y: 58.094,
    area: "World Map",
    region: null,
  },
];
